src/lib.rs
src/windows.rs

I'll need support for these keys in the emulator. :)

added support for Ctrl and Shift keys

---

src/lib.rs
src/windows.rs

Backquote/tilde key for Windows keyboard.

Added backquote/tilde key

---

Cargo.toml
src/lib.rs
src/os/mod.rs
src/os/redox/mod.rs

This pull request adds support for a new platform: [Redox OS](https://github.com/redox-os/redox).

Redox OS support

---

Cargo.toml
src/os/redox/mod.rs

Redox issue: https://github.com/redox-os/orbital/issues/20

Update orbclient to 0.3.14 on Redox

---

src/os/unix/mod.rs

Hi,
just run into following limitation when using minifb, hope this enhancement can help others.
Best
Johannes

unix: replaced scale functions with macro and added missing invocations

---

src/lib.rs

* Fixed a few mistakes in docs
* Convert `ignore` examples to `no_run` examples, so `cargo test` will
make sure they compiles.

Improvement in doc and doc tests

---

Cargo.toml
src/os/macos/mod.rs
src/os/unix/mod.rs
src/os/windows/mod.rs

Added raw-window-handle support
Closes #104

Raw window handle

---

src/os/unix/x11.rs
src/os/windows/mod.rs

X11 seems to work just fine.
Would be nice if someone can test this on windows.

[Testing] Implement is_active() on windows and x11

---

examples/image.rs
examples/julia.rs
examples/menu.rs
examples/mouse.rs
examples/multi.rs
examples/noise.rs
examples/title_cursor.rs
examples/transparent.rs
src/lib.rs
src/os/redox/mod.rs
src/os/unix/wayland.rs
src/os/unix/x11.rs
src/os/windows/mod.rs

This will partially resolve https://github.com/emoon/rust_minifb/issues/133
Implemented:
- X11
- Wayland
- Redox(couldnt test so far)

Transparency

---

src/error.rs

Implemented std::error::Error for minifb::Error

---

src/lib.rs
src/native/macosx/MacMiniFB.m
src/os/macos/mod.rs
src/os/redox/mod.rs
src/os/unix/mod.rs
src/os/unix/wayland.rs
src/os/unix/x11.rs
src/os/windows/mod.rs

Currently missing OSX implementation, would appreciate if someone could do it.

[WIP] Cursor visibility

---

Cargo.toml
src/key_handler.rs
src/rate.rs

Remove usage of the time crate.

---

README.md

Just a tiny fix to help newcomers :)

Update README.md to include mention of Wayland support

---

src/os/posix/wayland.rs

change default pointer visibility to true on wayland

---

src/os/windows/mod.rs

Use the correctly calculated window flags for both AdjustWindowRect and CreateWindowExW

Fix size calculation of non-decorated windows (#245)

---

src/error.rs

Fixes  copy/paste issue in documentation comment for Error::WindowCreate.

Minor update to error.rs

---

src/os/posix/wayland.rs

use non blocking alternative as documented in EventQueue
fixes #256

fix: EventQueue::dispatch blocks until some events are available

---

src/os/posix/wayland.rs

Hello, I am using the sway Wayland compositor and the library works on the first run but after when I run a test program again, it panics. This commit fixes it (tested by running the `topmost` example from the repository), see below for details.
wlroots based compositor reuse the same FD for keymap, so after a first
read is done, the file is seeked to the end and the next read fails,
causing the following error:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err`
value: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }'
The Wayland documentation says the FD "can be memory-mapped to provide
a keyboard mapping description" and then "From version 7 onwards, the
fd must be mapped with MAP_PRIVATE by the recipient, as MAP_SHARED may
fail."
Although it is not …

Memory-map the keymap FD on Wayland to fix EOF error

---

src/os/posix/wayland.rs

- Make the character callback use the key converted through the keymap, instead of trying to perform a direct conversion.
- Store a persistent keymap_state, instead of creating a new one every time. This makes sure that modifiers such as shift/capslock/ctrl are taken into account.
Closes #288.

wayland: Fix key character callback

---

src/native/macosx/MacMiniFB.m

Only lightly tested.
Should fix #287

Fix get_window_position for multiscreen setups on macOS.

---

src/lib.rs
src/os/posix/wayland.rs
src/os/posix/x11.rs

Deprecate limit_update_rate

---

examples/image.rs
src/key_handler.rs
src/lib.rs
src/os/posix/wayland.rs
src/os/posix/x11.rs
src/os/wasm/mod.rs

Reverts emoon/rust_minifb#359 because it breakes image example

Revert "fix image example buffer size calculation"

---

examples/image.rs
src/lib.rs

Fix image example

---

Cargo.toml
src/lib.rs
src/os/wasm/mod.rs

This PR fixes incompatible dependencies being brought into the build when building for the web.

Fix wasm compilation error

---

src/os/posix/x11.rs

This PR fixes the memory leaks mentioned in issue #357.

Fix memory leaks
