src/windows.rs

Since I need a second window now, here's the (possibly easiest) way to fix the duplicate class problem.

Ignore the "Class already exists" error in multiple-window application

---

README.md

The example code on `README.md` requires the `use` line to have the modules available when compiling.
Without it the example can't compile.

Include needed modules on the example code

---

src/os/windows/mod.rs

Hello,
I think replacing `buffer.iter().cloned().collect()` with `buffer.to_vec()` can noticeably improve the time spent in `update_with_buffer()` on Windows - Debug builds. 
When compiling with `--release` there is not much of a performance difference.
Here are the times spent in `window.update_with_buffer(&buffer)` using a `1280x720` framebuffer.
|   | Before | After |
|---|---|---|
| Debug | `120 ms` | `52 ms` |
| Release | `2.4 ms` | `2.2 ms` |

Improve debug performance of update_with_buffer on windows

---

src/os/unix/mod.rs

Found this while I was looking at the backspace issue on Linux - period key is not handled and it's something that my emulator uses, too!

Support period key on *nix.

---

src/os/redox/mod.rs

A typo in the new bounds checking code (900deba9a7851417c0253b57feba4a089f18b12a) broke the Redox port.

Fix Redox build

---

Cargo.toml

kernel32-sys 0.1.4 won't compile on my system:
rustc 1.24.0-nightly (8503b3ff8 2017-12-04)
binary: rustc
commit-hash: 8503b3ff822c1ed01c89773d30e4e10b886d77a5
commit-date: 2017-12-04
host: x86_64-pc-windows-gnu
release: 1.24.0-nightly
LLVM version: 4.0

Update kernel32-sys to 0.2.2 on Windows

---

Cargo.toml

The `homepage` key is meant for dedicated library websites, a link to the repository is already provided by the `repository` key.

Cargo.toml: Remove homepage link

---

src/lib.rs

Hi there!
I came here to add missing `Debug` impls. While doing so I noticed a few strange things which I tried to fix in the second commit. I don't quite understand why some modules were public but `doc(hidden)` (e.g. `pub mod os;`) and why some public items were `doc(hidden)` despite being used (e.g. `Key` and `Result`).
I hope these changes are OK! If not, just tell me what to change (I can also just remove some of the commits).

Add debug impls

---

src/key_handler.rs
src/lib.rs
src/os/macos/mod.rs
src/os/redox/mod.rs
src/os/unix/mod.rs
src/os/windows/mod.rs

I'm looking into making a Rust version of @Javidx9 's olcPixelGameEngine: https://github.com/OneLoneCoder/olcPixelGameEngine
Not much progress yet, but a good way to learn Rust for sure!
Anyhow, so far it seems that minifb is the nearest thing I can find that does the low level portion of what I'm trying to do, except for the fact that it doesn't let you determine if a key has just been released.
This PR adds the is_key_released method to address that shortfall.
I guess that the version could be bumped to 0.12.0 as I'm adding a new function, but I figured you could do that if you felt it was in keeping with what you're doing.

Added Window.is_key_released

---

src/key.rs

This PR simply adds the `Eq, Ord, PartialOrd and Hash` traits to the derive on top of the Key enum. It allows Keys to be stored in Sets, among other QOL things.

Add additional derived traits to Key enum

---

Cargo.toml
src/os/redox/mod.rs

Orbital windows are non-transparent by default now.
The commit where this was changed in Orbital: https://gitlab.redox-os.org/redox-os/orbital/commit/ef814901d0bc5a41860764e2b8b84f2c87a6e864

Bump orbclient to 0.3.20 on Redox, remove alpha handling hacks

---

src/os/unix/mod.rs

This helps the `check_buffer_size` run against the actual window size, which stops us from segfaulting if the window size has changed unexpectedly, e.g. because a window manager is evil.
This improves #66, but by no means fixes it (the examples still *panic* on start here (i3), they just don't segfault).

raise shared_data update

---

examples/mouse.rs
examples/multi.rs
examples/noise.rs
examples/title_cursor.rs
src/os/unix/key_mapping.rs
src/os/unix/mod.rs

Handle, to some extent, resizing under x11.
The middle of the event loop is perhaps not the best place to reallocate the image, but it is the simplest. Specifically, there are issues with error handling; at the moment, it just panics (`expect`).
I also fiddled the examples, `noise` and `mouse` now support resizing properly (i.e. they handle updating the buffer), and `multi` and `title_cursor` ask for non-resizable windows.
This should hopefully finally fix #66. It may introduce #71.

x11 and examples: resize

---

src/lib.rs

Closes #88 
I also added just to the example, a function (`from_u8_rgb`) that shows how to properly encode the RGB value. If you want, this function could be moved to the crate itself.

Improve documentation for method `update_with_buffer` of `Window`

---

src/os/unix/mod.rs

A program which creates a window with this library when the requested window size is taller than the screen size will crash because the two following lines do not take into this case.
```rust
let x = (d.screen_width - width) / 2;
let y = (d.screen_height - height) / 2;
```
The patchwork assigns this processed value when the window size is smaller than the screen size or 0 else.

fix 'attempt to subtract with overflow' bug

---

src/os/unix/mod.rs

Currently we interned `WM_DELETE_WINDOW` but does not call `XSetWMProtocols` to listen to it, causing a fatal error when closing the window by clicking "X". This patch fixes the issue.

Fix window close handling

---

.gitignore
examples/noise.rs
src/key_handler.rs
src/lib.rs
src/os/macos/mod.rs
src/os/redox/mod.rs
src/os/unix/mod.rs
src/os/unix/x11.rs
src/os/windows/mod.rs

See #150 
Adds a method `get_keys_released` to all `Window` implementations and extends the noise example to call it. This is the inverse of `get_keys_pressed` method in that it will fill the returned `Vec` with `Keys` that were released in the last update, rather than pressed.

add get_keys_released method to Window

---

src/error.rs

std::error::Error::description is deprecated, so I changed the
fmt::Display implementation to rely on fmt::Debug implementation, which,
in turn, return human-readable messages like description was doing

Change Error to use custom fmt::Debug messages

---

src/lib.rs
src/native/macosx/MacMiniFB.m
src/os/macos/mod.rs

This functionality is useful for utility apps that he developer wants to float above other windows
WindowOptions now has a topmost property denoting whether the window should be the topmost window.  The mfb_topmost function will set the NSWindow level property to NSFloatingWindowLevel if WindowOptions::topmost is true, otherwise it will be 0 (normal).

Added Topmost/Always on Top functionality to MacOS 

---

src/native/macosx/MacMiniFB.m

Removed NSLog(@"Names %@", [g_library functionNames]); debug call from src/native/macosx/MacMiniFB.m

Removing some legacy Debug information

---

examples/topmost.rs
src/os/windows/mod.rs

Most of this was taken from #159. This does not include the API addition of adding a topmost call on Window.
That should probably be in another PR. And the doc fixes as well.
Used implementation from https://github.com/emoon/rust_minifb/pull/159#discussion_r401374050
Co-authored-by: phillvancejr <phillipvancejr@gmail.com>
Co-authored-by: Daniel Collin <daniel@collin.com>

Support topmost functionality in Windows

---

src/lib.rs
src/os/macos/mod.rs
src/os/posix/mod.rs
src/os/windows/mod.rs

Added always on top functionality to Windows. Topmost functionality (always on top) can be achieved at window creation by setting WindowOptions::topmost to true, or after creation by calling Window::topmost(bool). This api works on MacOS and Windows.
I tested the Windows implementation using Wine. I'm assuming it will work properly on a real machine. On unix instead of calling unimplemented! The topmost function just returns void so that nothing breaks

Added Topmost (always on top) functionality to Windows

---

src/os/posix/x11.rs

There was a typo in the mappings, right bracket doesn't work.

Fix Key::RightBracket not working on POSIX

---

src/os/windows/mod.rs

Mouse positions went past the right side and bottom of the window even with discard and clamp mouse modes. This fixed things with the mouse example and seems to match what other backends do.
On a side note, the TODO-comments look stale as I didn't see any odd behavior with resizing after the fix.

Windows: Fix mouse positions not honoring MouseMode

---

examples/drop.rs
src/os/windows/mod.rs

This PR updates the Windows winuser `Drop` implementation to use `winuser::DestroyWindow(...)` instead of `winuser::CloseWindow(...)`. According to the [docs](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-closewindow), `CloseWindow()` "Minimizes (but does not destroy) the specified window.".  This should allow the Window to be properly destroyed once it falls out of scope.
I have also added a small example `cargo run --example drop` that tests the behavior. Feel free to remove this if not needed. Have left it there in case it was helpful to quickly test this behavior across other OS.

Fix: winuser | DestroyWindow

---

src/error.rs

The old implementation of Debug for Error would only print what type of error it was. Not what caused the error. Whereas, Display would print the type of error and what caused the error. This seemed backwards to what it should be, so I flipped them.

Make Debug for Error include the sub-error.

---

src/os/posix/wayland.rs

The xkbcommon_sys crate seems to have been updated today, and now the minifb project won't compile. 
We can fix this by updating XKB_KEYMAP_FORMAT_TEXT_v1 to XKB_KEYMAP_FORMAT_TEXT_V1.

Update xkb_keymap reference

---

src/os/windows/mod.rs

The `SelectObject()` call accepts a `HGDIOBJ` which is typecast to a
`std::os::raw::c_void` when building using libstd, and is its own thing
when building with std disabled:
winapi/0.3.9/src/winapi/lib.rs.html:
```rust
#[cfg(feature = "std")]
pub use std::os::raw::c_void;
#[cfg(not(feature = "std"))]
pub enum c_void {}
```
This patch uses the winapi c_void as the typecast as necessary.

windows: use c_void from winapi

---

src/os/posix/wayland.rs

This fixes the problem with the window automatically closing itself when
the mouse goes over it.

Fix wayland missing cursor.

---

src/lib.rs

I noticed the description was missing words in the doc: https://docs.rs/minifb/0.19.2/minifb/
The README seems fine though.

Add missing words in description

---

examples/julia.rs
examples/menu.rs
examples/mouse.rs
examples/title_cursor.rs
src/key_handler.rs
src/os/posix/common.rs
src/os/posix/mod.rs
src/os/posix/wayland.rs
src/os/posix/x11.rs

Fix the clippy warnings that appear when running `cargo clippy` on linux. There may be other warnings on windows and/or macos.

address clippy lints

---

Cargo.toml
src/os/posix/wayland.rs

We I created the previous PR to update versions I didn't realize that `xkb` still depends on the previous version.
Also there are some issues in the new version: https://github.com/meh/rust-xkbcommon-sys/issues/7

Revert bump of `xkbcommon-sys`

---

src/native/macosx/OSXWindowFrameView.m

Two obvious mistakes, but hard to find when you are only told that an invalid memory access happened in a specific place.

macOS: Fix segmentation fault when resizing window

---

src/key_handler.rs
src/lib.rs
src/os/posix/wayland.rs

Add a callback for key events. This includes complete events such as
Shift, not just text events.
A default handler is provided for backwards compatibility.

key_handler: add a callback for key events

---

src/key_handler.rs
src/lib.rs

Add a callback for key events. This includes all events such as Shift, not just text events. This allows for getting more complete information on keys as they're pressed.
An empty default handler is provided for backwards compatibility.

inputcallback: add a callback for key events

---

src/lib.rs
src/native/macosx/MacMiniFB.m
src/os/macos/mod.rs
src/os/posix/mod.rs
src/os/posix/wayland.rs
src/os/posix/x11.rs
src/os/windows/mod.rs

For a current project I wanted to store the layout of windows on the screen to reuse for the next session.
I added `get_position` to the window.
It is tested on macos, and windows - with a single display connected.
I created a stub for linux, which always returns 0,0. It compiles, but is untested due to lack of a system to test on.
It will need some rework for multi display systems, but I don't have one to do that.
I tried to keep the formatting, and style in line with the original.

Add getter for window position.

---

Cargo.toml

When building some apps, it throws an error at  `winapi::um::fileapi::GetFullPathNameW` as "could not find `fileapi` in `um`". This PR fixes the error.

Add fileapi feature gate of winapi

---

src/os/posix/wayland.rs
src/os/posix/x11.rs

This addresses #291 where compilation failed on a Raspberry Pi with mismatched types errors.

Use coercion on types failing compilation on 64 bit raspbian bullseye

---

src/os/windows/mod.rs

Things were not compiling for my ARM64 Windows 11 machine. With this simple addition it works again.

ARM and AARCH64 Windows Support

---

src/os/windows/mod.rs

I Could not get menus to be removed on windows, even when running the example.
Looking at the code, it looks like there is a flag missing as per https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-removemenu#parameters.
This PR simply adds the "By Position" flag that indicates that the menus should be removed by position, not by ID (which is what the `for i in 0..self.menus.len()` seem to indicate is the case).

set byposition flag when removing menus on windows

---

src/os/posix/x11.rs

FFI signature of `x11::xlib::XTranslateCoordinates` expects a `*mut c_ulong`.
Changing the cast to that  instead of `*mut u64` makes this compile on 32-bit
systems.
I can also confirm that the various examples run fine inside an arm32v7
docker image via X11.

Fix compilation of minifb's X11 binding for 32-bit

---

examples/title_cursor.rs
src/os/posix/x11.rs

A new private function Window::set_title_raw added so it can be called from both places where the window title is being changed.
Added a dynamic window title changing to title_cursor example for "visual testing" the issue.

X11: Fix changing window title, fixes #322

---

src/lib.rs

made set_background_color function take u8 rgb values instead of usize and removed clamp function since it was only used to make sure that said usize color values were between 0 and 255, while u8 values are by definition guaranteed to be in that range

Moved runtime color bounds checks to compile time

---

src/native/macosx/MacMiniFB.m

If a `NSMenu` does not have `setAutoenablesItems:NO` then any `NSMenuItem`s cannot be disabled. This fixes the functionality of disabling menu items on macOS.
Realistically down the line a test case should be added to the `menu` example for disabled menus, but it's not a huge concern and I'm not putting it in this PR.
I've tested this PR with the menu example which has no change (good!) and a personal project which is working as expected. This does not impact menu items that are enabled by default through minifb.

Fix disabling menu items on macOS

---

build.rs
src/native/posix/scalar.c

I discovered that minifb uses and compiles non-Rust code for a few use cases, one of which is to make the image scaling functions optimized on Linux in all profiles.
I'm not keen on this approach, as it means that minifb is reliant on a separate compiler to build the project. As an example, I am using minifb for one of my projects, and someone who wanted to run it got a compiler error when compiling it on Linux. They didn't have a C++ compiler installed:
Ideally, I'd like to not depend on a C/C++ compiler on Linux.
One option is writing the scalar functions in Rust into their own crate, make minifb depend on that crate and ensure the profile for that dependency is always optimized:
```toml
[profile.dev.package.minifb-scalar]
opt-level = 3
```
although that means there is a second crate to …

Make scalar code plain C

---

src/lib.rs

Previous deprecation notice pointed to a function that doesn't exist, this PR fixes that oversight.

Fix `limit_update_rate`'s deprecation notice

---

CHANGELOG.md

- #353 part two.
- Should've tackled that in the PR mentioned above, but I did not notice that the same mistake is present in the changelog.

Fix v0.26 entry in `CHANGELOG.md`

---

Cargo.toml
examples/wasm.rs
src/key_handler.rs
src/lib.rs
src/os/wasm/mod.rs
src/rate.rs

This PR makes some changes to how `Window`s are instantiated on wasm targets
- The `title` parameter in `Window::new()` has been replaced with `container`, which takes an element the canvas should be appended to
- Allows more control over where and how to embed a minifb canvas in web projects, and still allows the user to change the window title with `set_title`
- Rustdoc new window example has been updated for wasm32 target
- `set_cursor_visibility` now properly sets the the html canvas cursor style
- `is_active` now checks if the canvas element is focused

Wasm Improvements

---

src/os/windows/mod.rs

* Fixes https://github.com/emoon/rust_minifb/issues/365
Windows handles are pointers by type, but dereferencing these doesn't have any meaning and naturally may just crash (it does ;-)) - if you're lucky this is caught by Rust debug checks complaining about alignment, if you're not it's just a segfault.
Tested this on https://github.com/Wumpf/minifb_wgpu_web_and_desktop (at https://github.com/Wumpf/minifb_wgpu_web_and_desktop/commit/e39be06686b9b8662d27fd4cb0a3787dfaee172d)

Fix incorrect deferencing of Windows window handles

---

.github/workflows/ci.yml
src/lib.rs
src/os/wasm/mod.rs
src/rate.rs

Also, fixed various warnings & added a CI step to check the wasm target.
The reason [`getContext`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext) have to be delayed here is that this stateful: Once `getContext` is called with one type of context (`2d`, `webgl` or `webgpu`), any future call with a different type will fail.
-> Previously, it was not possible to use the canvas with a WebGL/WebGPU context since `minifb` would call `.get_context("2d")` during initialization.
Tested this on https://github.com/Wumpf/minifb_wgpu_web_and_desktop (at https://github.com/Wumpf/minifb_wgpu_web_and_desktop/commit/e39be06686b9b8662d27fd4cb0a3787dfaee172d)

[wasm] Fix raw handles, delay `getContext` call to be WebGPU compatible

---

src/os/windows/mod.rs

..and make windows' hwnd a non-option, removing lots of 'unwrap'.
I think I actually broke the `hinstance` in a previous PR! Turns out that `GetWindowLongPtrW(raw_hwnd, GWLP_HINSTANCE)` always returned null. So instead, I make now sure to use the same hinstance that was used when creating the window in the  rist place.
I noticed this when trying to use wgpu with a Vulkan backend on windows which requires a valid hinstance. I didn't notice so far because wgpu always fell back to OpenGL because it (correctly) couldn't create a surface for Vulkan. But now when disabling OpenGL that error of course bubbled up.

Fix windows hInstance for raw window handle

---

build.rs

This fixes cross-compilation, as beforehand it would require the Linux windowing system features (X11 or Wayland) even when building for windows (on a linux host).
Tested locally using both linux->linux compilation (both that it builds with default-features, and errors without) and linux->windows (doesn't) error)
Fixes #373

Build - Remove use of `cfg!` and instead inspect `TARGET`

---

src/os/posix/wayland.rs

See commit message for the fix made and issue for context (don't want to duplicate information).
Fixes: #377
P.S. suggest merge commit as is since it contains valuable information.

Released keys detection is broken on Wayland
